//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSearchParameter
    {
        public int Id { get; set; }
        public double LoanAmmount { get; set; }
        public int Term { get; set; }
        public double Interest { get; set; }
        public int InterestPeriod { get; set; }
        public System.DateTime CalculationTime { get; set; }
        public string UserId { get; set; }
    }
}
