//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSearchParameter
    {
        public int Id { get; set; }
        public double LoanAmmount { get; set; }
        public int Term { get; set; }
        public int InterestPeriodId { get; set; }
        public System.DateTime CalculationTime { get; set; }
        public string UserId { get; set; }
        public double InterestFirstPeriod { get; set; }
        public Nullable<double> InterestSecondPeriod { get; set; }
        public Nullable<double> InterestThirdPeriod { get; set; }
        public int TermFirstPeriod { get; set; }
        public Nullable<int> TermSecondPeriod { get; set; }
        public Nullable<int> TermThirdPeriod { get; set; }
    
        public virtual Period Period { get; set; }
    }
}
